dist: xenial
language: python
matrix:
  include:
  - python: 3.7
    env: TOXENV=py37
script:
- "./version.sh"
deploy:
  provider: pypi
  user: __token__
  on:
    all_branches: true
  skip_existing: true
  skip_cleanup: true
  password:
    secure: Ncb9zvXlG8u1fl07Vmo9xG8BHFXrO11CmvaNQy2znsFVtOFGZI20GkHq9BsQS8aJ/4BOidbBU37gBdxjXikOBTqWXdVYwyOeYEFrUZtgELCKcqx+2GXhCYP7sIlvNFGetGePnajY7OWKgYU3f6D2zPswn30culC6E3BPXHX3QrAuhXqi71wGWgmyUQ6zh5VIH5DlZHCdkMv36TQqqcRiMy4A2vTnZ6ugMBEUqP8TDkoJ5/B6oxkZt2ZPsJyTRfTpVO+l0qfZ/rsPUgmULnHYqqmhdbuveUQJDSYfcjmauuFwLfXb62uzG8clMePzXreKLFbQ82dAeNslP0rcGy+Kpqhmd+fBD6uUlgIiO1ddP9iKFi00b8Dlz86lmHOqVxtDu/UZUpnEmi9MzXMartzIAYaV7DeA3XuPqhqcgvfnzpNZQBUa0nL+G3k7B8jh4xQf6ZPJYPPxBjVc3nKoSMJuKuaj/Ogqf7FPDE3FDRDqkA1hLUP11cbRciJlKtKqGAohh6WhK7uI3A1yfwxlZgxbHT9G3PJeJZRWxym0F+lxqZkxweO4Z3tVsYIVDq7KcGseCpFZ+IECMU/lVWQRc/mTB0jPIPwTrS2hN6lJMyTfoApqgTTyqT9R96+7213m+cbOf/oy4loIDyWhZMml6WKeborI/7mySAz0eWDUit5DhsI=
