dist: xenial
language: python
matrix:
  include:
  - python: 3.7
    env: TOXENV=py37
script:
- "./version.sh"
deploy:
  distributions: sdist bdist_wheel
  provider: pypi
  user: __token__
  on:
    all_branches: true
  password:
    secure: LUpnmZRA8qrhR/6vK9oMGcD9eXbBaN/2PIk4F8ROGJEKkLlERVIH4d6ZsSPvxlshbV4lrJgl1joNrmkM49TKbSBxy8ZeyOApe28/nakJ4OZEucFgg4WITmEX7yxVorZ9BYTq1WPGclvJni3ODeI8tkjwrGCqrvcX8NuOQx/XtGa0mOw0xUFViqkZsqlkCzdPmzNeB2/yboZQ7GOemSRqRE7tJk9jFud67b4WNYOqz6Nf7/ahvF6epuecONXJzqr9/C8UE2fTXVvm212dwbdOAWCNb4LP/62wXcTp7MkUMydjYnalfQ62n0cxCDFZqSiPIBrUnvlGHJYb2G+eMt4Naxlsh4+vXafy2SrzubPXPBkPcLhMmYtek1fEfyFODgNX7U7baeimeqs/gGtewzUx6ybNhiLFLP6DJNJJ8E26ehxiuCRef7yJ4bXBs9cwYDVxxerXm1T+mAwwl4k+yF59Jr6sXnTgSSP3RQZ6hgJPH4AhfNCsQfgyxHEICI2QGny7UirxoUpqhrw55Vy8HGJEdrjr0162lSeJxkrlGTKcrhRfzwh5GRB3PqnNKfoVRn/8iqhn1n39H/nKMh92C5q7+vu4p9ivalHsXEx53Fyx/vpNNswejBcutUaFn15YOfYWysYdk83rtrMrBLoThYH15x0v7KxmPRF0HY5Jh0qUvKA=
