dist: xenial
language: python
cache: pip
matrix:
  include:
  - python: 3.7
    env: TOXENV=py37
script:
- "./version.sh"
before_install:
- sudo apt-get install -y liblo-dev
install:
- pip install -r requirements.txt
- pip install .
deploy:
  provider: pypi
  user: __token__
  password:
  - secure: kFxFTA333Fl1wju/iSbjxuYVDmWv1nwsTX5LKTdG2NOyDo9P3NhuXLa5yDjOgGAklck95hGzHLY39V/RRw2mV/uaLQThnpq+671rGPJnvqZErxDk4nrOb3+e2/9rk2t6W+SvGt4BL1wVhWXPWPOiVb81GIuVlNKxbR3r+t5T7QFg7Jx4G5IqHt0m/pwqFX4JlsHT7jAcga9rjyZjeJIVbXOrN3xl4Dk4EbsqKgzOvvUe47ttFI55FGL30USpXYMO+K0g/J2GCg3dBPvAkuZMoHorN0XsEYwDsRfh3RU01S9pASTG5DJusp5g6GH4izNf++f2wa8NtI/NU1dBvLrMmWr6T1sq7l89DOS06lu18B33kbU8tagEdnF0CH3R7G5vpC+syx2kETjCFSdSQUgQfylv9geY6QNEpvShsF/BJrMDiIpOL/XWB8wZgHKty9t9LBpmU9SIpr4Ba7vdp0CZInxE3RA2QKPn9+fQszKWUvkrIIUaGj5gJHD5qVo7sHmsc8+lBk88mWHwzWiVoFfrPbEumY2fPNRy7KMt8UC1irzK/tAPrIhh/ptdIveACprxjjuLNYYW2YprKUvUvgk5v6JjWdPSO1vQdCwe4wStf8s+ZRkKLtEZx1BN/S++Vzitp7UejjI04Zf98mwVKmOYxf0LH5TPjfDC4WZUz8c+0/M=
  - secure: B6LNcM1yR3bTxzmzWU5z2+MBaFTWnezqnrwzUkM2Gv4I1WUB2Awlzr6wjfEcRIGLL5g9vAPqlXr8TErIyJTPckxWLgAJLyQu9QDBdlVqK7plzJL9UBuMKYogJoMvT2A0tjQpMkY1BvPImi97UiNqmvnq1b5vq461Bjp/MhUtJlmHU5f5WjhqcDTSlrd+gajEBJsu6ap/K+cOtBMKKyQzlu434MUH9dnfWAeBOpG/cysVFPXXIZ5boVV8TpZ8tO4sh7E3C6ekDldL+b8QXvcq4LEPhUxRMJzP9rofDm7DESaC04Opiudscv9lTvPAPHUIV8n3U2+7gpLXYcUC5mhsk9IEEhoE1USe6UKyYSgeYiAd3TF2ucSNPhyDE6CwQHkyy9Nzzj7XODND9BdLE/HD7yHskN4WSfGoZF/NvneQxwb2nk3HxgT8g0dUIb8PICiVtbI/KFzPL/MKuOw075oejqeIhxL1EwbvSiMeZSqSapIrq3zv5EAMa08i3dI8qDNNMIqnaN009fK8c6DSaqMx27F0v5/nzBVCe+VeUMMqqy2pRrV8691mA1UlpBDFcYp0YlPi8It6/q0HlU5Vpk2V/D+DNdq3wpR9MS9KC/FNVkr+59WjmOmNVceAFTjJHZlVr3oAsSwiHagUFIpKmIrn5EXEFXWk72aPQp9TugO0rIo=
  on:
    all_branches: true
