dist: xenial
language: python
cache: pip
matrix:
  include:
  - python: 3.7
    env: TOXENV=py37
script:
- "./version.sh"
before_install:
- sudo apt-get install -y liblo-dev
install:
- pip install -r requirements.txt
- pip install .
deploy:
  distributions: sdist bdist_wheel
  skip_upload_docs: true
  provider: pypi
  user: __token__
  password:
  - secure: B6LNcM1yR3bTxzmzWU5z2+MBaFTWnezqnrwzUkM2Gv4I1WUB2Awlzr6wjfEcRIGLL5g9vAPqlXr8TErIyJTPckxWLgAJLyQu9QDBdlVqK7plzJL9UBuMKYogJoMvT2A0tjQpMkY1BvPImi97UiNqmvnq1b5vq461Bjp/MhUtJlmHU5f5WjhqcDTSlrd+gajEBJsu6ap/K+cOtBMKKyQzlu434MUH9dnfWAeBOpG/cysVFPXXIZ5boVV8TpZ8tO4sh7E3C6ekDldL+b8QXvcq4LEPhUxRMJzP9rofDm7DESaC04Opiudscv9lTvPAPHUIV8n3U2+7gpLXYcUC5mhsk9IEEhoE1USe6UKyYSgeYiAd3TF2ucSNPhyDE6CwQHkyy9Nzzj7XODND9BdLE/HD7yHskN4WSfGoZF/NvneQxwb2nk3HxgT8g0dUIb8PICiVtbI/KFzPL/MKuOw075oejqeIhxL1EwbvSiMeZSqSapIrq3zv5EAMa08i3dI8qDNNMIqnaN009fK8c6DSaqMx27F0v5/nzBVCe+VeUMMqqy2pRrV8691mA1UlpBDFcYp0YlPi8It6/q0HlU5Vpk2V/D+DNdq3wpR9MS9KC/FNVkr+59WjmOmNVceAFTjJHZlVr3oAsSwiHagUFIpKmIrn5EXEFXWk72aPQp9TugO0rIo=
  on:
    all_branches: true
